config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :calendar, only: :index
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'calendar#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def index
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :start_date, :end_date)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/calendar/index.html.haml
%header
.all-header
  %h2 My calendar
  - if user_signed_in?
    .user_nav.user_login
      = link_to "Log out", destroy_user_session_path, method: :delete, class: 'btn new_btn'
      = link_to 'New Event', new_event_path , class: 'btn new_btn'
  - else
    .user_login
      = link_to "Log in", new_user_session_path, class: 'btn new_btn'
      = link_to "Sign up", new_user_registration_path, class: 'btn new_btn'
  = yield

%body
%br
.main
  .side-content

  .main-content
    #calendar
    %br
    
%footer
  %p.footer
    my first app 2019

app/views/events/_form.html.haml
= form_with model: @event,local: true do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :start_date
    = f.datetime_select :start_date
  .field
    = f.label :end_date
    = f.datetime_select :end_date
  .actions
    = f.submit 'Save'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', root_path

app/views/events/index.html.haml
%body

%h1 Listing events
.btn.home-btn
  =link_to 'return home', root_path

%table
  %thead
    %tr
      %th Title
      %th Details 
      %th Start date
      %th End date
  %tbody
    - @events.each do |event|
      %tr
        %td= event.title
        %td= event.description
        %td= event.start_date.strftime("%Y/%m/%d %H:%M")
        %td= event.end_date.strftime("%Y/%m/%d %H:%M")
        %td.btn= link_to 'Show', event
        %td.btn= link_to 'Edit', edit_event_path(event)
        %td.btn= link_to 'Destroy', event, method: :delete, data: { confirm: 'この項目は削除されます' }
  

app/views/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', root_path

app/views/events/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @event.title
%p
  %b Description:
  = @event.description
%p
  %b Start date:
  = @event.start_date
%p
  %b End date:
  = @event.end_date

= link_to 'Edit', edit_event_path(@event)
\|
= link_to 'Back', root_path
\|
= link_to 'Destroy', @event, method: :delete, data: { confirm: 'この項目は削除されます' }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Calendartodo
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "assets/favicon2.png", :rel => "icon", :type => "image/png"}/
    %script{:src => "gcal.min.js"}
    -# %script{src: "//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js", type: "text/javascript"}
    -# %script{src: "//cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.2/fullcalendar.js", type: "text/javascript"}
    -# %script{src: "//cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.2/gcal.js", type: "text/javascript"}
  %body
    = yield

    

app/views/tasks/_calendar.html.haml
.contents.row
  - @tasks.each do |task|
    .content_post{style: "background-image: url(#{task.image});"}
      %p= task.text
      %span.name
        = task.name

app/views/tasks/index.html.haml
.wrapper
  =render "calendar"